// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdrzAIlxdnjlAyK7KbMTm69OCDaEApwDY',
    appId: '1:982254527659:web:8d052916c02941222e43ee',
    messagingSenderId: '982254527659',
    projectId: 'fair-carbon-project',
    authDomain: 'fair-carbon-project.firebaseapp.com',
    databaseURL: 'https://fair-carbon-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fair-carbon-project.appspot.com',
    measurementId: 'G-QW5C53JTFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZNCzShkP9G4pYjBEaZ7SVker1Wtj8IsM',
    appId: '1:982254527659:android:0348d5373f9ade9c2e43ee',
    messagingSenderId: '982254527659',
    projectId: 'fair-carbon-project',
    databaseURL: 'https://fair-carbon-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fair-carbon-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDUPq1Vw2KdfXXKwQzsUdsXxu6lYO3BWw',
    appId: '1:982254527659:ios:fad7f48c3d0a4d952e43ee',
    messagingSenderId: '982254527659',
    projectId: 'fair-carbon-project',
    databaseURL: 'https://fair-carbon-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fair-carbon-project.appspot.com',
    iosBundleId: 'com.example.carbonFootprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDUPq1Vw2KdfXXKwQzsUdsXxu6lYO3BWw',
    appId: '1:982254527659:ios:801ef1858fce5b9d2e43ee',
    messagingSenderId: '982254527659',
    projectId: 'fair-carbon-project',
    databaseURL: 'https://fair-carbon-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fair-carbon-project.appspot.com',
    iosBundleId: 'com.example.carbonFootprint.RunnerTests',
  );
}
